# Generated by Django 2.1.7 on 2019-02-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categorie',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
