# Generated by Django 2.1.7 on 2019-02-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('flat', 'Flachstab'), ('round', 'Rundstab'), ('square', 'Vierkant'), ('pipe', 'Rohr')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('steel', 'S235JR'), ('copper', 'Kupfer'), ('iron', 'Eisen')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, height_field=250, upload_to='img/item', width_field=250),
        ),
        migrations.RemoveField(
            model_name='item',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.AddField(
            model_name='item',
            name='categorie',
            field=models.ManyToManyField(to='item.Categorie'),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.ManyToManyField(to='item.Material'),
        ),
    ]
