# Generated by Django 2.1.7 on 2019-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190212_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='categorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(height_field=250, upload_to='img/item', width_field=250),
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(max_length=50),
        ),
    ]
