# Generated by Django 2.1.7 on 2019-02-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20190212_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.Categorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Material'),
        ),
    ]
