# Generated by Django 2.1.7 on 2019-02-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20190212_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\Patrick\\Desktop\\Code\\Django\\Stahl_Kaltalog\\media'),
        ),
    ]
