# Generated by Django 2.1.7 on 2019-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20190212_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='categorie',
            name='multiplicator',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
