# Generated by Django 2.1.7 on 2019-02-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20190212_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='multiplicator',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
