# Generated by Django 2.1.7 on 2019-02-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_material_multiplicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='multiplicator',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='multiplicator',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
