# Generated by Django 2.1.7 on 2019-02-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20190212_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='multiplicator',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
