# Generated by Django 2.1.7 on 2019-02-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20190212_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
